#!/usr/bin/env python3
"""
Generate tests/e2e_flow_with_usage_plans.robot from testdata/e2e_usage_plans.csv.

Each CSV row produces 6 Robot test cases:
    <tc_id> Step 01 Onboard EC And BU
    <tc_id> Step 02 Create APN And CSR Journey
    <tc_id> Step 03 SIM Range And Product Type
    <tc_id> Step 04 Create And Process SIM Order
    <tc_id> Step 05 Activate SIMs And Perform Usage
    <tc_id> Step 06 Generate Invoice

Auto-runs before every execution via run_tests.py.
"""

import csv
import os
import sys

ROOT_DIR   = os.path.dirname(os.path.abspath(__file__))
CSV_PATH   = os.path.join(ROOT_DIR, "testdata", "e2e_usage_plans.csv")
ROBOT_PATH = os.path.join(ROOT_DIR, "tests", "e2e_flow_with_usage_plans.robot")

STEPS = [
    ("01", "Onboard EC And BU",                  "E2E Step 01 Onboard    {tc_id}"),
    ("02", "Create APN And CSR Journey",         "E2E Step 02 APN And CSR"),
    ("03", "SIM Range And Product Type",         "E2E Step 03 SIM Range And Product Type"),
    ("04", "Create And Process SIM Order",       "E2E Step 04 SIM Order And Processing"),
    ("05", "Activate SIMs And Perform Usage",    "E2E Step 05 Activate And Usage"),
    ("06", "Generate Invoice",                   "E2E Step 06 Invoice"),
    ("07", "Create Second CSR Journey",          "E2E Step 07 Second CSR Journey"),
    ("08", "Device Plan Change And Validate",    "E2E Step 08 Device Plan Change"),
]

SETTINGS = """\
*** Settings ***
Documentation     E2E Flow With Usage — Plan-Duration Matrix (step-per-phase per plan).
...
...               Each plan row in testdata/e2e_usage_plans.csv gets 6 step test cases.
...               File is auto-generated by generate_e2e_plan_tests.py — do not edit manually.
...
...               Fixed overrides (same for all plans):
...                   - SIM count: 2
...                   - APN type: Private (created APN reused in CSR Journey)

Library     SeleniumLibrary
Library     RequestsLibrary
Library     Collections
Library     String
Library     OperatingSystem
Resource    ../resources/keywords/e2e_keywords.resource
Resource    ../resources/keywords/usage_keywords.resource
Library     ../libraries/ConfigLoader.py
Variables   ../variables/login_variables.py
Variables   ../variables/onboard_customer_variables.py
Variables   ../variables/apn_variables.py
Variables   ../variables/csr_journey_variables.py
Variables   ../variables/sim_range_variables.py
Variables   ../variables/sim_order_variables.py
Variables   ../variables/product_type_variables.py
Variables   ../variables/order_processing_variables.py
Variables   ../variables/device_state_variables.py
Variables   ../variables/usage_variables.py

Suite Setup       Run Keywords    Load Environment Config From Json    ${ENV}    AND    E2E Suite Setup
Suite Teardown    Close All Browsers
Test Setup        Ensure Session Is Active
Test Teardown     Run Keyword If Test Failed    Capture Page Screenshot

"""

VARIABLES = """\
*** Variables ***
${E2E_EC_NAME}              ${EMPTY}
${E2E_BU_NAME}              ${EMPTY}
${E2E_ORDER_ID}             ${EMPTY}
${E2E_EC_ID}                ${EMPTY}
${E2E_BU_ID}                ${EMPTY}
${E2E_ACTIVATED_IMSIS}      ${EMPTY}
${E2E_IMSI_DATA}            ${EMPTY}
${PLAN_SIM_QUANTITY}        ${2}

"""

KEYWORDS = """\
*** Keywords ***
Get Plan Data From CSV
    [Arguments]    ${tc_id}
    ${csv_path}=    Set Variable    ${CURDIR}/../testdata/e2e_usage_plans.csv
    ${content}=     OperatingSystem.Get File    ${csv_path}
    @{lines}=       Split To Lines    ${content}
    FOR    ${line}    IN    @{lines}[1:]
        ${line}=    Strip String    ${line}
        Continue For Loop If    '${line}' == ''
        @{cols}=    Split String    ${line}    ,
        ${row_id}=    Strip String    ${cols}[0]
        IF    '${row_id}' == '${tc_id}'
            ${tp2}=    Set Variable If    ${cols.__len__()} > 5    ${cols}[5]    ${EMPTY}
            ${bp2}=    Set Variable If    ${cols.__len__()} > 6    ${cols}[6]    ${EMPTY}
            RETURN    ${cols}[3]    ${cols}[4]    ${tp2}    ${bp2}
        END
    END
    Fail    Plan data for '${tc_id}' not found in e2e_usage_plans.csv

E2E Step 01 Onboard
    [Arguments]    ${tc_id}
    Log    ============================================================    console=yes
    Log    STEP 01 - ONBOARD EC AND BU [${tc_id}]    console=yes
    Log    ============================================================    console=yes
    ${tariff_plan}    ${bundle_plan}    ${tariff_plan_2}    ${bundle_plan_2}=    Get Plan Data From CSV    ${tc_id}
    Log    [PLAN] Tariff Plan   : ${tariff_plan}    console=yes
    Log    [PLAN] Bundle Plan   : ${bundle_plan}    console=yes
    Log    [PLAN] Tariff Plan 2 : ${tariff_plan_2}    console=yes
    Log    [PLAN] Bundle Plan 2 : ${bundle_plan_2}    console=yes
    Set Suite Variable    ${CSRJ_DEFAULT_TARIFF_PLAN}    ${tariff_plan}
    Set Suite Variable    ${CSRJ_DEFAULT_BUNDLE_PLAN}    ${bundle_plan}
    Set Suite Variable    ${CSRJ_DEFAULT_TARIFF_PLAN_2}    ${tariff_plan_2}
    Set Suite Variable    ${CSRJ_DEFAULT_BUNDLE_PLAN_2}    ${bundle_plan_2}
    Log    [API] Sending SOAP onboarding request...    console=yes
    ${ec_name}    ${bu_name}=    E2E Onboard Account
    Set Suite Variable    ${E2E_EC_NAME}    ${ec_name}
    Set Suite Variable    ${E2E_BU_NAME}    ${bu_name}
    Log    [RESULT] EC Name : ${E2E_EC_NAME}    console=yes
    Log    [RESULT] BU Name : ${E2E_BU_NAME}    console=yes
    Log    STEP 01 COMPLETE    console=yes

E2E Step 02 APN And CSR
    Log    ============================================================    console=yes
    Log    STEP 02 - VERIFY ACCOUNT + CREATE APN + CSR JOURNEY    console=yes
    Log    ============================================================    console=yes
    Should Not Be Empty    ${E2E_EC_NAME}    Step 01 must run first - EC name is empty
    Should Not Be Empty    ${E2E_BU_NAME}    Step 01 must run first - BU name is empty
    Log    [WAIT] Sleeping 5 min for backend to process onboarded account...    console=yes
    Sleep    300s    reason=Waiting 5 min for backend to process onboarded account
    Log    [UI] Verifying account on UI - EC=${E2E_EC_NAME} BU=${E2E_BU_NAME}    console=yes
    ${passed}=    Run Keyword And Return Status
    ...    E2E Verify Account On UI    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    IF    not ${passed}
        Log    [WARN] Account not found on first attempt - waiting another 5 min and retrying...    console=yes
        Sleep    300s    reason=Retry wait - another 5 min for account to appear
        Go To    ${BASE_URL}ManageAccount
        Sleep    3s
        Wait For App Loading To Complete    timeout=60s
        E2E Verify Account On UI    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    END
    Log    [RESULT] Account verified on UI    console=yes
    Log    [UI] Creating Private APN for EC=${E2E_EC_NAME} BU=${E2E_BU_NAME}    console=yes
    E2E Create APN    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    Log    [RESULT] APN created : ${VALID_APN_NAME}    console=yes
    Log    [UI] Creating CSR Journey - Tariff=${CSRJ_DEFAULT_TARIFF_PLAN} Bundle=${CSRJ_DEFAULT_BUNDLE_PLAN} APN=${VALID_APN_NAME} (Private)    console=yes
    E2E Create CSR Journey With Specific Plans    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    Log    [RESULT] CSR Journey created    console=yes
    Log    STEP 02 COMPLETE    console=yes

E2E Step 03 SIM Range And Product Type
    Log    ============================================================    console=yes
    Log    STEP 03 - SIM RANGE + PRODUCT TYPE + EXPAND LIMITS    console=yes
    Log    ============================================================    console=yes
    Log    [UI] Creating SIM Range (ICCID/IMSI + MSISDN)...    console=yes
    E2E Create SIM Range
    Log    [RESULT] SIM Range created    console=yes
    Log    [UI] Creating Product Type and assigning EC=${E2E_EC_NAME}...    console=yes
    E2E Create Product Type And Assign EC    ${E2E_EC_NAME}
    Log    [RESULT] Product Type created and assigned    console=yes
    Log    [UI] Expanding EC/BU SIM limits by ${PLAN_SIM_QUANTITY}...    console=yes
    E2E Expand EC And BU SIM Limits    ${E2E_EC_NAME}    ${E2E_BU_NAME}    ${PLAN_SIM_QUANTITY}
    Log    [RESULT] SIM limits expanded    console=yes
    Log    STEP 03 COMPLETE    console=yes

E2E Step 04 SIM Order And Processing
    Log    ============================================================    console=yes
    Log    STEP 04 - SIM ORDER + ORDER PROCESSING    console=yes
    Log    ============================================================    console=yes
    Should Not Be Empty    ${E2E_EC_NAME}    Step 01 must run first - EC name is empty
    Log    [UI] Creating SIM Order - EC=${E2E_EC_NAME} BU=${E2E_BU_NAME} Qty=${PLAN_SIM_QUANTITY}    console=yes
    E2E Create SIM Order    ${E2E_EC_NAME}    ${E2E_BU_NAME}    ${PLAN_SIM_QUANTITY}
    ${order_id}=    E2E Capture Order ID    ${E2E_BU_NAME}
    Set Suite Variable    ${E2E_ORDER_ID}    ${order_id}
    Log    [RESULT] Order ID : ${E2E_ORDER_ID}    console=yes
    ${ec_id}    ${bu_id}=    E2E Fetch Account IDs From DB    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    ${ec_id_str}=    Convert To String    ${ec_id}
    ${bu_id_str}=    Convert To String    ${bu_id}
    Set Suite Variable    ${E2E_EC_ID}    ${ec_id_str}
    Set Suite Variable    ${E2E_BU_ID}    ${bu_id_str}
    Log    [DB] EC ID=${E2E_EC_ID} / BU ID=${E2E_BU_ID}    console=yes
    Log    [SSH] Running create order script...    console=yes
    E2E Run Create Order Script
    Log    [UI] Validating order status - In Progress...    console=yes
    E2E Validate Order Status New To In Progress    ${E2E_ORDER_ID}
    Log    [RESULT] Order status = In Progress    console=yes
    Log    [SSH] Generating and uploading response files for order ${E2E_ORDER_ID}...    console=yes
    E2E Generate And Upload Response Files    ${E2E_ORDER_ID}
    Log    [SSH] Running read order script...    console=yes
    E2E Run Read Order Script
    Log    [UI] Validating order status - Completed...    console=yes
    E2E Validate Order Status Completed    ${E2E_ORDER_ID}
    Log    [RESULT] Order status = Completed    console=yes
    Log    [UI] Validating SIMs in Warm state for BU=${E2E_BU_NAME} (expecting ${PLAN_SIM_QUANTITY})...    console=yes
    E2E Validate SIMs In Warm State    ${E2E_BU_NAME}    ${PLAN_SIM_QUANTITY}
    Log    [RESULT] SIMs in Warm state    console=yes
    Log    STEP 04 COMPLETE    console=yes

E2E Step 05 Activate And Usage
    Log    ============================================================    console=yes
    Log    STEP 05 - ACTIVATE SIMs + INJECT USAGE + VALIDATE    console=yes
    Log    ============================================================    console=yes
    Should Not Be Empty    ${E2E_BU_NAME}     Step 01 must run first - BU name is empty
    Should Not Be Empty    ${E2E_ORDER_ID}    Step 04 must run first - Order ID is empty
    Log    [SOAP] Approving order ${E2E_ORDER_ID}...    console=yes
    E2E Update Order Status To Approved    ${E2E_ORDER_ID}
    Log    [RESULT] Order approved    console=yes
    Log    [UI] Activating ${PLAN_SIM_QUANTITY} SIMs for BU=${E2E_BU_NAME}...    console=yes
    ${imsis}    ${imsi_data}=    E2E Activate SIMs And Capture IMSIs
    ...    ${E2E_BU_NAME}    count=${PLAN_SIM_QUANTITY}
    Set Suite Variable    ${E2E_ACTIVATED_IMSIS}    ${imsis}
    Set Suite Variable    ${E2E_IMSI_DATA}          ${imsi_data}
    Log    [RESULT] Activated IMSIs : ${E2E_ACTIVATED_IMSIS}    console=yes
    Length Should Be    ${E2E_ACTIVATED_IMSIS}    ${PLAN_SIM_QUANTITY}
    ...    msg=Expected ${PLAN_SIM_QUANTITY} activated IMSIs - got ${E2E_ACTIVATED_IMSIS}
    Log    [API] Injecting usage for all ${PLAN_SIM_QUANTITY} IMSIs...    console=yes
    E2E Perform Usage For All IMSIs    @{E2E_IMSI_DATA}
    Log    [RESULT] Usage injected    console=yes
    Log    [UI] Validating usage in UI...    console=yes
    E2E Validate Usage In UI    @{E2E_IMSI_DATA}
    Log    [RESULT] Usage validated in UI    console=yes
    Log    STEP 05 COMPLETE    console=yes

E2E Step 06 Invoice
    Log    ============================================================    console=yes
    Log    STEP 06 - GENERATE INVOICE    console=yes
    Log    ============================================================    console=yes
    ${bu_id_str}=    Convert To String    ${E2E_BU_ID}
    Should Not Be Equal    ${bu_id_str}    ${EMPTY}    Step 04 must run first - BU ID is empty
    Log    [API] Generating invoice for BU ID=${bu_id_str}...    console=yes
    E2E Generate And Download Invoice    ${bu_id_str}
    Log    [RESULT] Invoice generated and downloaded    console=yes
    Log    STEP 06 COMPLETE    console=yes

E2E Step 07 Second CSR Journey
    Log    ============================================================    console=yes
    Log    STEP 07 - CREATE SECOND CSR JOURNEY (DIFFERENT PLAN)    console=yes
    Log    ============================================================    console=yes
    Should Not Be Empty    ${E2E_EC_NAME}    Step 01 must run first - EC name is empty
    Should Not Be Empty    ${E2E_BU_NAME}    Step 01 must run first - BU name is empty
    Log    [UI] Creating second CSR Journey with different plan for EC=${E2E_EC_NAME} BU=${E2E_BU_NAME}...    console=yes
    E2E Create Second CSR Journey With Different Plan    ${E2E_EC_NAME}    ${E2E_BU_NAME}
    Log    [RESULT] Second CSR Journey created    console=yes
    Log    STEP 07 COMPLETE    console=yes

E2E Step 08 Device Plan Change
    Log    ============================================================    console=yes
    Log    STEP 08 - DEVICE PLAN CHANGE ON ONE ACTIVATED SIM    console=yes
    Log    ============================================================    console=yes
    Should Not Be Empty    ${E2E_BU_NAME}    Step 01 must run first - BU name is empty
    Log    [UI] Performing device plan change for BU=${E2E_BU_NAME}...    console=yes
    E2E Perform Device Plan Change On One Activated SIM And Validate    ${E2E_BU_NAME}
    Log    [RESULT] Device plan change completed and validated    console=yes
    Log    STEP 08 COMPLETE    console=yes
"""


def read_plans(csv_path):
    plans = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            tc_id = row.get("tc_id", "").strip()
            tags  = row.get("tags",  "").strip()
            if tc_id:
                plans.append({"tc_id": tc_id, "tags": tags})
    return plans


def build_test_cases(plans):
    lines = ["*** Test Cases ***\n"]
    for plan in plans:
        tc_id = plan["tc_id"]
        raw_tags = plan["tags"] or f"e2e    e2e-with-usage    {tc_id}    plan-duration    regression"
        tag_tokens = [t for t in raw_tags.split() if t]
        tags_line = "    ".join(tag_tokens)
        lines.append(f"# {'='*55}\n")
        lines.append(f"#  {tc_id}\n")
        lines.append(f"# {'='*55}\n")
        for step_nn, step_name, keyword in STEPS:
            kw_call = keyword.format(tc_id=tc_id)
            lines.append(f"{tc_id} Step {step_nn} {step_name}\n")
            lines.append(f"    [Tags]    {tags_line}\n")
            lines.append(f"    {kw_call}\n")
            lines.append("\n")
        lines.append("\n")
    return "".join(lines)


def generate(csv_path=CSV_PATH, robot_path=ROBOT_PATH):
    if not os.path.isfile(csv_path):
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    plans = read_plans(csv_path)
    if not plans:
        print(f"ERROR: No valid rows found in {csv_path}", file=sys.stderr)
        sys.exit(1)

    content = SETTINGS + VARIABLES + build_test_cases(plans) + KEYWORDS

    with open(robot_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    print(f"Generated {len(plans)} plan(s) x {len(STEPS)} steps = {len(plans) * len(STEPS)} test cases")
    for p in plans:
        print(f"  + {p['tc_id']}")
    print(f"Written to: {robot_path}")


if __name__ == "__main__":
    generate()